### ISSUE TITLE
Discriminator

### ISSUE THREAD

**Issue by Butterfies** [njucckevin/ADS-Cap#2]
Hi, @njucckevin : 
In config.py `parser.add_argument('--recheck_model_path', default='./models/Discriminator/model_3800.pt')` the discriminator model_3800.pt could not be found. Do I need to run train_recheck.py to get the discriminator model ?

**Comment by njucckevin** [comment]
Hi,
I just add the model_3800.pt in `models/Discriminator/model_3800.pt`. You can try to see if it works.

**Comment by njucckevin** [comment]
It is just a style classification model based on LSTM.

**Comment by Butterfies** [comment]
Hi, I have one more question，when i Training【step1】```
Traceback (most recent call last):
  File "./train_cvae.py", line 197, in <module>
    ppl_ro, ppl_fu, ppl_pos, ppl_neg = eval_ppl(config, global_step, 'val')
  File "ADS/utils/eval_metrics_cvae.py", line 454, in eval_ppl
    ppl_ro = read_ppl(ppl_ro_path)
  File "ADS/utils/eval_metrics_cvae.py", line 430, in read_ppl
    tokens = last_line.split()
UnboundLocalError: local variable 'last_line' referenced before assignment
```
I think there is a problem with line 454-457 of the code in the eval_metrics_cvae.py, ```
    ppl_ro = read_ppl(ppl_ro_path)
    ppl_fu = read_ppl(ppl_fu_path)
    ppl_pos = read_ppl(ppl_pos_path)
    ppl_neg = read_ppl(ppl_neg_path)
``` , It should be ` ppl_ro = read_ppl(out_txt_dir_ro)` , right?

**Comment by wxpqq826615304** [comment]
Hi,
Can you provide a set of trained model parameters, I trained the model with your code, acc is only over 70%.
Then I remembered that I had an error when I was running this code, and it made me realize that my training process may be different from yours
![image](https://github.com/njucckevin/ADS-Cap/assets/67469948/fd37a69e-4683-4ee1-9836-dfb600c8cf00)

**Comment by gWeiXP** [comment]
> It is just a style classification model based on LSTM.

Hi,
Can you provide a set of trained model parameters, I trained the model with your code, acc is only over 70%.
Then I remembered that I had an error when I was running this code, and it made me realize that my training process may be different from yours
![image](https://github.com/njucckevin/ADS-Cap/assets/67469948/c9b0c0bd-9a91-4698-b864-12ff59c8d075)

**Comment by njucckevin** [comment]
@wxpqq826615304 It seems that the embedding layer size is mismatched with the checkpoint. Have you check the vocab_size of your model? Alternatively, I upload a new vocab.pkl file in /data/vocab.pkl.
And I also upload the trained model checkpoint of cvae_k0.03_s1.0_ft in https://box.nju.edu.cn/d/bff4e27f2291466a860a/. You can have a try.
